In [1]:
# read n space separated  integers from user and find sum of all mid terms in the number
n=int(input("Enter no of numbers : "))
integers=list(map(str,input("Enter space seperated numbers having three digits  : ").split()))[:n]
l=[]
Sum = 0
for num in integers:
    l.append(num[1])
for i in l:
    Sum=Sum+int(i)
print(Sum)   
            

Enter no of numbers : 3
Enter space seperated numbers having three digits  : 123 456 789
15


- Types of data in Real time
   1. Quantitative
      - Represents the size/volume of data
      - Discrete and continuous
         - This type of data is fixed/constant
           - Ex: numbers on die: varies from 1 to 6
             - distance, color,nationality,size,etc.,
         - Continous data means the value/data is continous
   2. Qualitative
      - Data is observed and placed in terms of category 
        - Ex: Data submission in feed back form 
- Dataand Statistics 
    - nominal, Ordinal, Interval and Ratio 
       - Nominal means data is categorized on the basics of names 
          - Ex: Nationality ,Color,Gender
       - Ordinal means data is based upon the order of values
          - Feed back form 
       - Interval means a range of daa values 
           - time interval in clock  :2:15 is in between 2&3
       - Ratio means data is meaningfully added subracted multiplied and diveded (ratios) 
           

#### Importing module
- Numpy
- Pandas
- Matplotlib and seaborn

In [2]:
import numpy


In [3]:
# numpy directory
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [4]:
# version of numpy
numpy.__version__

'1.20.1'

### Numpy 
- ***Numpy stands for numerical python***
- ***Which is used to deal with array type of data and Scientific computation***

### **Array Creation**
- ***array() is the submodule in numpy module***
- ***np.array(iterable data type)***

In [5]:
print(numpy.array([3,4,5,6,7,8]))

[3 4 5 6 7 8]


In [6]:
t=numpy.array((5,6,7,8,9))


In [7]:
print(t)

[5 6 7 8 9]


In [8]:
ar=numpy.array([45.5,44.76,67.6,55.88])
ar

array([45.5 , 44.76, 67.6 , 55.88])

In [9]:
fl=numpy.array([34.56,2334.67,67.445,67.69],dtype="float")
fl

array([  34.56 , 2334.67 ,   67.445,   67.69 ])

In [10]:
st=numpy.array((123.45,56.23,46.89),dtype='str')
print(st)

['123.45' '56.23' '46.89']


In [11]:
rn=numpy.array(range(10))
print(rn)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
r2 =numpy.array(range(1,8))
print(r2)

[1 2 3 4 5 6 7]


In [13]:
r3=numpy.array(range(0,80,10))
print(r3)

[ 0 10 20 30 40 50 60 70]


In [14]:
#printing dimensins of array
r3.ndim 

1

In [15]:
# Multi dimensional array
l2=numpy.array([[23,4,5,5],[3,75,2,6]])
print(l2)


[[23  4  5  5]
 [ 3 75  2  6]]


In [16]:
# says no of elements
l2.size

8

In [17]:
# gives row size and coloumn size
l2.shape

(2, 4)

In [18]:
l2.itemsize

4

In [19]:
st.itemsize

24

In [20]:
# 3-Dimensional array
l3=numpy.array([[[23,4,5,5],[3,75,2,6],[2,4,7,5]]])
l3
print(l3)

[[[23  4  5  5]
  [ 3 75  2  6]
  [ 2  4  7  5]]]


In [21]:
l2.ndim

2

In [22]:
l3.ndim

3

In [23]:
i=numpy.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
l5=numpy.array([12,34,56],ndmin=10)
l5

array([[[[[[[[[[12, 34, 56]]]]]]]]]])

In [25]:
z=numpy.zeros(4)
z

array([0., 0., 0., 0.])

In [26]:
z=numpy.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
o=numpy.ones(7)
o

array([1., 1., 1., 1., 1., 1., 1.])

In [28]:
o=numpy.ones((7,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
f=numpy.full(4,"hi")
f

array(['hi', 'hi', 'hi', 'hi'], dtype='<U2')

In [30]:
f=numpy.full((7,7),"hi")
f

array([['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']], dtype='<U2')

In [31]:
f.fill('D')
f

array([['D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['D', 'D', 'D', 'D', 'D', 'D', 'D']], dtype='<U2')

In [32]:
f.dtype="int"
f

array([[68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0],
       [68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0],
       [68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0],
       [68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0],
       [68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0],
       [68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0],
       [68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0, 68,  0]])

In [33]:
ln=numpy.linspace(10,200,10)
ln

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [34]:
len(ln)

10

In [35]:
print(numpy.arange(25))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [36]:
ln.reshape(5,2)

array([[ 10.        ,  31.11111111],
       [ 52.22222222,  73.33333333],
       [ 94.44444444, 115.55555556],
       [136.66666667, 157.77777778],
       [178.88888889, 200.        ]])

### Random()
- ***It is used generate radom integers in a range.***
- ***random.randint(range)***

In [37]:
import numpy as n
rns=n.random.randint(10)
rns

3

In [41]:
# multiple random variables
lw,up=map(int,input().split())
ri =n.random.randint(lw,up,8)
ri.reshape(2,4)

1 10


array([[5, 4, 2, 2],
       [5, 7, 6, 6]])

In [42]:
ri

array([5, 4, 2, 2, 5, 7, 6, 6])

In [43]:
# Random integers between 0 and 1 of size(3,7)
n.random.random((1,7)) 

array([[0.36503604, 0.98936347, 0.20283635, 0.45347   , 0.39258765,
        0.25977029, 0.49557059]])

In [44]:
#size
n.random.rand(1,7)

array([[0.59810326, 0.57751541, 0.0493184 , 0.95375126, 0.4336849 ,
        0.65374418, 0.06822633]])

In [45]:
# Random integers between -1 and 1 of size(3,7)
n.random.randn(1,7)

array([[-0.57450001, -0.27658625,  0.65976801,  1.29482357, -0.34600359,
         0.33700559, -0.02358744]])

In [46]:
# if third integer is not mentioned it does 50 partitiions by default
n.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [47]:
n.linspace(7,70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [50]:
help(n.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

### <u>Accessing the array elements</u>
-   ***using index we recognize array elwments***
-   ***Indexing is of 3 types***
-   ***+ve indexing,-ve indexing and fancy indexing***
1. **+ve indexing**
   - ***Traverse from left to right***
2. **-ve indexing**
   - ***Traverse from  right to left***
3. **Fancy indexing**
   - ***Condition Based index***

In [51]:
r=n.random.randint(50,200,25).reshape(5,-1)
r

array([[ 50, 147, 195, 154,  50],
       [177,  98, 133, 184, 102],
       [177, 190, 192,  85, 152],
       [ 92,  91,  92, 155,  94],
       [136, 198,  59,  99, 121]])

In [52]:
rr=n.random.randint(50,200,25).reshape(-1,5)
rr

array([[ 78, 124, 188,  88,  81],
       [ 90,  79, 175, 166,  68],
       [128, 138, 104, 142, 135],
       [ 80, 147, 197, 122, 122],
       [ 60, 165, 149, 111, 105]])

In [53]:
rr[3]

array([ 80, 147, 197, 122, 122])

In [54]:
rr[::-1]

array([[ 60, 165, 149, 111, 105],
       [ 80, 147, 197, 122, 122],
       [128, 138, 104, 142, 135],
       [ 90,  79, 175, 166,  68],
       [ 78, 124, 188,  88,  81]])

In [55]:
sub=r[:,1:4]
for line in sub:
    for val in line:
        if val%2==1:
            print(val)


147
195
133
85
91
155
59
99


In [56]:
r

array([[ 50, 147, 195, 154,  50],
       [177,  98, 133, 184, 102],
       [177, 190, 192,  85, 152],
       [ 92,  91,  92, 155,  94],
       [136, 198,  59,  99, 121]])

In [57]:
r.transpose()

array([[ 50, 177, 177,  92, 136],
       [147,  98, 190,  91, 198],
       [195, 133, 192,  92,  59],
       [154, 184,  85, 155,  99],
       [ 50, 102, 152,  94, 121]])

In [58]:
r<100

array([[ True, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [False, False,  True,  True, False]])

In [59]:
r[r<100]

array([50, 50, 98, 85, 92, 91, 92, 94, 59, 99])

In [60]:
l=[]
for i in r:
    for j in i:
        if(j<100):
            l.append(j)
print(l)

[50, 50, 98, 85, 92, 91, 92, 94, 59, 99]


In [61]:
r

array([[ 50, 147, 195, 154,  50],
       [177,  98, 133, 184, 102],
       [177, 190, 192,  85, 152],
       [ 92,  91,  92, 155,  94],
       [136, 198,  59,  99, 121]])

In [62]:
s=n.random.randint(1,7)
print(s+r)

[[ 54 151 199 158  54]
 [181 102 137 188 106]
 [181 194 196  89 156]
 [ 96  95  96 159  98]
 [140 202  63 103 125]]


In [63]:
print(s-r)

[[ -46 -143 -191 -150  -46]
 [-173  -94 -129 -180  -98]
 [-173 -186 -188  -81 -148]
 [ -88  -87  -88 -151  -90]
 [-132 -194  -55  -95 -117]]


In [64]:
s/r

array([[0.08      , 0.02721088, 0.02051282, 0.02597403, 0.08      ],
       [0.02259887, 0.04081633, 0.03007519, 0.02173913, 0.03921569],
       [0.02259887, 0.02105263, 0.02083333, 0.04705882, 0.02631579],
       [0.04347826, 0.04395604, 0.04347826, 0.02580645, 0.04255319],
       [0.02941176, 0.02020202, 0.06779661, 0.04040404, 0.03305785]])

In [65]:
help(n.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [66]:
r+rr

array([[128, 271, 383, 242, 131],
       [267, 177, 308, 350, 170],
       [305, 328, 296, 227, 287],
       [172, 238, 289, 277, 216],
       [196, 363, 208, 210, 226]])

In [67]:
r*rr

array([[ 3900, 18228, 36660, 13552,  4050],
       [15930,  7742, 23275, 30544,  6936],
       [22656, 26220, 19968, 12070, 20520],
       [ 7360, 13377, 18124, 18910, 11468],
       [ 8160, 32670,  8791, 10989, 12705]])

In [68]:
r.mean()

128.92

In [69]:
r.sum()

3223

In [70]:
print(r.max())
r.min()

198


50

In [71]:
r

array([[ 50, 147, 195, 154,  50],
       [177,  98, 133, 184, 102],
       [177, 190, 192,  85, 152],
       [ 92,  91,  92, 155,  94],
       [136, 198,  59,  99, 121]])

In [72]:
r[0]

array([ 50, 147, 195, 154,  50])

In [73]:
n.log(10)

2.302585092994046

In [74]:
n.exp(1)

2.718281828459045

In [75]:
n.exp(1)

2.718281828459045

In [76]:
n.exp(1)

2.718281828459045

In [77]:
n.exp(1)

2.718281828459045

In [78]:
n.exp(n.log(7))

6.999999999999999

In [79]:
n.exp(1)

2.718281828459045

In [80]:
n.log(n.exp(7))

7.0

In [81]:
def greater(x,y):
    l=[]
    for i in range(len(x)):
        if(x[i]>y[i]):
            l.append(x[i])
        else:
            l.append(y[i])
    return l

In [82]:
print(greater([4,5,6],[7,3,9]))

[7, 5, 9]
